import { GameSession } from '@/entity/game_session.entity';
import { User } from '@/entity/user.entity';
import { generateNumCode } from '@/utils/common.util';
import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

@Injectable()
export class SessionService {
  constructor(
    @InjectRepository(GameSession)
    private readonly userRepository: Repository<User>,
  ) {}

  async findAll(): Promise<User[]> {
    return await this.userRepository.find();
  }

  async createAutoGeneratedUser(): Promise<User> {
    const user = new User();
    // TODO :: create with name generator
    const code = generateNumCode(4);
    user.nickname = `유저${code}`;
    user.autoGenerated = true;
    return await this.userRepository.save(user);
  }
}
