import { User } from '@/entity/user.entity';

export class UserDto {
  nickname: string;
  autoGenerated: boolean = true;

  static from(dto: Partial<User>) {
    const user = new UserDto();
    user.nickname = dto.nickname;
    user.autoGenerated = dto.autoGenerated;
    return user;
  }
}
