import { Controller, Get, Post } from '@nestjs/common';
import { AppService } from '../services/app.service';
import { UserService } from '@/services/user.service';
import { User } from '@/entity/user.entity';
import { UserDto } from '@/dto/user.dto';

@Controller('user')
export class UserController {
  constructor(private readonly userService: UserService) {}

  @Post('/create/auto-generated')
  async createAutoGeneratedUser(): Promise<UserDto> {
    const user: User = await this.userService.createAutoGeneratedUser();
    return UserDto.from(user);
  }
}
